# OneBot11 网关
ws_url = "ws://127.0.0.1:30001"

# 欢迎开关 & 群列表
welcome_enabled = true
welcome_groups = ["524364253", "562897832", "715664650", "917654757", "747114944", "583980948"]

# 回复词开关 & 群列表
trigger_enabled = true
trigger_groups  = ["524364253", "562897832", "715664650", "917654757", "747114944", "583980948", "1012508116"]

# 日志群
log_group = "583980948"

# 迎新延迟与发送间隔（秒）
welcome_delay_seconds = 120
welcome_gap_seconds = 3

# 识别的称呼 & 触发冷却
names = ["雪桃", "洛拉娜", "洛拉娜·奥蕾莉娅", "Lorana", "Lorana Aurelia"]
trigger_cooldown_seconds = 1

# 超管/测试指令
super_user_id = "732899935"
test_command = "Another Me，测试迎新"

# 备用：若无法自动拿 self_id，则用这个作为合并转发的 sender
forward_sender_id = "2162317375"

# 合并转发发出后再 @ 的延迟（秒）
group_forward_then_at_delay_seconds = 3.0

# 允许 @ 机器人触发
mention_trigger_enabled = true